Repository StudyForces/sources-ui, pull requests merged in 2022-06, with the labels that each got.

#9 Constants Updates
  src/Constants.js
Labels: bug, enhancement

#8 Creating simple editor for regions
  package-lock.json
  package.json
  src/components/upload-edit/UploadEditPage.js
  src/components/upload-edit/UploadRectsEditor.js
Labels: enhancement

#11 Update UI, fix scaling, preview OCR if present
  src/api/sourceUploads.js
  src/components/upload-edit/UploadEditPage.js
  src/components/upload-edit/UploadRectsEditor.js
Labels: bug, enhancement

#14 Formula OCR
  package-lock.json
  package.json
  src/components/upload-edit/UploadRectsEditor.js
  src/index.scss
Labels: enhancement

#17 OCR Review
  src/App.js
  src/api/index.js
  src/api/ocr.js
  src/api/problems.js
  src/api/sourceUploads.js
  src/components/ocr-review/OCRResultReviewCard.js
  src/components/ocr-review/OCRReviewPage.js
  src/components/ocr-review/ProblemSubmissionForm.js
  src/components/upload-edit/UploadEditPage.js
  src/components/upload-edit/UploadRectsEditor.js
Labels: enhancement

#18 Add Problem UI
  src/App.js
  src/api/problems.js
  src/components/misc/Header.js
  src/components/misc/ProblemForm.js
  src/components/ocr-review/OCRResultReviewCard.js
  src/components/ocr-review/OCRReviewPage.js
  src/components/ocr-review/ProblemSubmissionForm.js
  src/components/problem-review/ProblemReviewPage.js
  src/components/problems/ProblemRow.js
  src/components/problems/ProblemsPage.js
  src/components/problems/ProblemsTable.js
Labels: bug, enhancement

#19 Add preview, use custom Latex component, style changes
  package-lock.json
  package.json
  src/components/helpers/cropImage.js
  src/components/misc/Latex.js
  src/components/misc/ProblemForm.js
  src/components/ocr-review/OCRResultReviewCard.js
  src/components/ocr-review/OCRReviewPage.js
  src/components/ocr-review/ProblemSubmissionForm.js
  src/components/problems/ProblemRow.js
  src/components/upload-edit/UploadEditPage.js
  src/components/upload-edit/UploadRectsEditor.js
  src/index.scss
Labels: bug, enhancement

#20 Some changes in APIs, add ability to work with ProblemAttachments
  src/api/index.js
  src/api/sourceUploads.js
  src/api/uploads.js
  src/components/misc/ProblemAttachmentsForm.js
  src/components/misc/ProblemForm.js
  src/components/ocr-review/OCRReviewPage.js
  src/components/problems/ProblemRow.js
  src/components/upload-edit/UploadRectsEditor.js
Labels: enhancement

#21 OCRReviewPage: handle multiple pages
  src/components/ocr-review/OCRReviewPage.js
Labels: bug, enhancement

#22 Fix OCR delete
  src/api/ocr.js
  src/components/upload-edit/UploadEditPage.js
  src/components/upload-edit/UploadRectsEditor.js
Labels: bug
